Feature/add build and branch policy name (#12)
Added build and branch name policy jobs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,37 +3,56 @@ name: SonarQube
 on:
   push:
     branches:
-      - main
+      - 'main'
   pull_request:
-    types: [opened, synchronize, reopened]
+    branches:
+      - main
 
 jobs:
-  build:
-    name: Build and analyze
+  branch-name-policy:
+    name: branch-name-policy
     runs-on: ubuntu-latest
+    steps:
+      - name: Check PR source branch name
+        shell: bash
+        run: |
+          BRANCH="${{ github.head_ref }}"
+          echo "PR head ref: $BRANCH"
+          if [[ "$BRANCH" =~ ^(release/|hotfix/|feature/|bugfix/|test).* ]]; then
+            echo "Allowed branch pattern: $BRANCH"
+            exit 0
+          else
+            echo "::error ::Branch name '$BRANCH' is not allowed to merge into main. Allowed patterns: release/*, hotfix/*, feature/*, bugfix/*, test*"
+            exit 1
+          fi
+  build:
+    name: Build
+    runs-on: ubuntu-latest
+    container:
+      image: eclipse-temurin:11-jdk
+    permissions:
+      contents: read
+      pull-requests: write
+
     steps:
       - name: Checkout source code to docker ubuntu container
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: Set up JDK 11
-        uses: actions/setup-java@v4
-        with:
-          java-version: 11
-          distribution: 'temurin'
-      - name: Cache SonarQube packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache Gradle packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.gradle/caches
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
-          restore-keys: ${{ runner.os }}-gradle
-      - name: Sonarqube scanning step
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: ./gradlew build sonar --info
+          token: ${{ secrets.PAT_GH_TOKEN }}
+          fetch-depth: 0
+      - name: Build project
+        run: ./gradlew build -x test
+
+#      - name: Cache SonarQube packages
+#        uses: actions/cache@v4
+#        with:
+#          path: ~/.sonar/cache
+#          key: ${{ runner.os }}-sonar
+#          restore-keys: ${{ runner.os }}-sonar
+#      - name: Sonarqube scanning step
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#        run: ./gradlew build sonar --info
+
+
+# test 2
